### ISSUE TITLE
Backoffice/ Project Initialisation

### ISSUE THREAD

**Issue by Akecel** [DeathCoinOfTheDoom/backoffice-landing-page#1]
- [x] Choisir la technologie
- [x] Installation du projet
- [x] Configuration
- [x] Push

**Comment by JessicaThi** [comment]
Choix techno : Vue.js
Installation du projet faite avec Nuxt.js

**Comment by Akecel** [comment]
@JessicaThi  Pense à bouger la tache dans inprogess( la je l'ai fait ;) ) je me chargerai de les fermer,
Et du coup si c'est bon, tu peux le push sur le répo ?

**Comment by Akecel** [comment]
@JessicaThi 

push le projet : 
- git init (dans le terminal au niveau du dossier de ton projet)
- git remote add origin https://github.com/DeathCoinOfTheDoom/backoffice-landing-page.git
- git push

Essaie de maintenir tes commit à jour, un commit par modification significative et en push pour chaque tache
